name: Build AyuGram Private

on:
  workflow_dispatch: 

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo apt-get clean
          df -h

      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Restore Cache
        uses: actions/cache/restore@v4
        with:
          path: tdesktop
          key: tdesktop-full-${{ github.run_id }}
          restore-keys: |
            tdesktop-full-
            
      - name: Clone or Pull AyuGram
        run: |
          if [ -d "tdesktop/.git" ]; then
            echo "Cache found! Updating repository..."
            cd tdesktop
            git pull
            git submodule update --init --recursive
            cd ..
          else
            echo "Cache not found! Cloning fresh repository..."
            git clone --recursive https://github.com/AyuGram/AyuGramDesktop.git tdesktop
          fi

      - name: Run Build
        run: |
          cd tdesktop
          docker run --rm \
            -u $(id -u) \
            -v "$PWD:/usr/src/tdesktop" \
            ghcr.io/telegramdesktop/tdesktop/centos_env:latest \
            /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
            -D TDESKTOP_API_ID=${{ secrets.MY_API_ID }} \
            -D TDESKTOP_API_HASH=${{ secrets.MY_API_HASH }}

      - name: Save Cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: tdesktop
          key: tdesktop-full-${{ github.run_id }}

      - name: Setup Rclone & Upload
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONFIG_DATA }}
        run: |
          sudo apt update && sudo apt install rclone -y
          mkdir -p ~/.config/rclone
          
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf
          
          cd tdesktop
          VERSION=$(git describe --tags --always)
          cd ..
          
          echo "Packing only the final executable..."
          tar -cJf ayugram-linux-${VERSION}.tar.xz -C tdesktop/out/Release/ AyuGram
          
          echo "Final compressed file size:"
          du -h ayugram-linux-${VERSION}.tar.xz

          echo "Starting upload to Google Drive..."
          rclone copy ayugram-linux-${VERSION}.tar.xz gdrive:AyuGramBuilds/ -v
          
      - name: Cleanup
        if: always()
        run: rm -rf ~/.config/rclone